replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: spark-candles.v12.trade
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: spark-candles-tls
      hosts:
        - spark-candles.v12.trade

vault:
  mount: production
